### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by prjemian** [prjemian/pysumreg#15]
As reported https://github.com/BCDA-APS/apstools/issues/1044#issuecomment-2495148841

<details>

```py
In [25]: RE(lineup2([signal], motor, -8, 1, 19, nscans=1, signal_stats=stats))
    ...: cen = stats._registers[signal.name].centroid
    ...: in_pos = abs(motor.position - cen) <= 0.001
    ...: print(f"{in_pos=!r}")
    ...: stats.report(); trim_plot_by_name(5, "noisy_det vs motor")


Transient Scan ID: 27     Time: 2024-11-22 18:30:30
Persistent Unique Scan ID: '82dd2d33-b1c0-442f-b7f1-f6962c23ff08'
New stream: 'primary'
+-----------+------------+------------+------------+
|   seq_num |       time |      motor |  noisy_det |
+-----------+------------+------------+------------+
|         1 | 18:30:30.6 |     -8.322 |     -0.047 |
|         2 | 18:30:30.6 |     -7.822 |     -0.070 |
|         3 | 18:30:30.6 |     -7.322 |     -0.001 |
|         4 | 18:30:30.6 |     -6.822 |      0.081 |
|         5 | 18:30:30.7 |     -6.322 |     -0.041 |
|         6 | 18:30:30.7 |     -5.822 |      0.058 |
|         7 | 18:30:30.7 |     -5.322 |     -0.044 |
|         8 | 18:30:30.7 |     -4.822 |     -0.025 |
|         9 | 18:30:30.7 |     -4.322 |      0.077 |
|        10 | 18:30:30.7 |     -3.822 |      0.023 |
Run aborted
Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py", line 1605, in _run
    msg = self._plan_stack[-1].send(resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py", line 480, in lineup2
    target = get_x_by_feature()
             ^^^^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py", line 435, in get_x_by_feature
    peak_too_wide = too_wide(stats)
                    ^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py", line 465, in too_wide
    fwhm = stats.sigma * factor_fwhm
           ^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/pysumreg/sum_registers.py", line 298, in sigma
    return math.sqrt((self.XXY - self.centroid * self.XY) / self.Y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: math domain error
|        11 | 18:30:30.7 |     -3.322 |      0.054 |
|        12 | 18:30:30.7 |     -2.822 |      0.098 |
|        13 | 18:30:30.8 |     -2.322 |      0.018 |
|        14 | 18:30:30.8 |     -1.822 |      0.098 |
|        15 | 18:30:30.8 |     -1.322 |      0.420 |
|        16 | 18:30:30.8 |     -0.822 |      0.721 |
|        17 | 18:30:30.8 |     -0.322 |      0.930 |
|        18 | 18:30:30.8 |      0.178 |      1.079 |
|        19 | 18:30:30.8 |      0.678 |      0.764 |
+-----------+------------+------------+------------+
generator rel_scan ['82dd2d33'] (scan num: 27)



---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[25], line 1
----> 1 RE(lineup2([signal], motor, -8, 1, 19, nscans=1, signal_stats=stats))
      2 cen = stats._registers[signal.name].centroid
      3 in_pos = abs(motor.position - cen) <= 0.001

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py:973, in RunEngine.__call__(self, *args, **metadata_kw)
    969         self._blocking_event.set()
    971     self._task_fut.add_done_callback(set_blocking_event)
--> 973 plan_return = self._resume_task(init_func=_build_task)
    975 if self._interrupted:
    976     raise RunEngineInterrupted(self.pause_msg) from None

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py:1109, in RunEngine._resume_task(self, init_func)
   1106 # if the main task exception is not None, re-raise
   1107 # it (unless it is a canceled error)
   1108 if exc is not None and not isinstance(exc, _RunEnginePanic):
-> 1109     raise exc
   1110 # Only try to get a result if there wasn't an error,
   1111 # (other than a cancelled error)
   1112 if exc is None:

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py:1751, in RunEngine._run(self)
   1749     exit_reason = str(err)
   1750     self.log.exception("Run aborted")
-> 1751     raise err
   1752 finally:
   1753     if not exit_reason:

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py:1605, in RunEngine._run(self)
   1602 # The normal case of clean operation
   1603 else:
   1604     try:
-> 1605         msg = self._plan_stack[-1].send(resp)
   1606     # We have exhausted the top generator
   1607     except StopIteration:
   1608         # pop the dead generator go back to the top

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py:480, in lineup2(detectors, mover, rel_start, rel_end, points, peak_factor, width_factor, feature, nscans, signal_stats, md)
    477 yield from _inner()  # Run the scan.
    478 nscans -= 1
--> 480 target = get_x_by_feature()
    481 if target is None:
    482     nscans = 0  # Nothing found, no point scanning again.

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py:435, in lineup2.<locals>.get_x_by_feature()
    433 stats = principal_signal_stats()
    434 peak_strong = strong_peak(stats)
--> 435 peak_too_wide = too_wide(stats)
    436 print(f"{feature=!r}")
    437 if peak_strong and not peak_too_wide:

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py:465, in lineup2.<locals>.too_wide(stats)
    463 try:
    464     x_range = stats.max_x - stats.min_x
--> 465     fwhm = stats.sigma * factor_fwhm
    466     return fwhm > width_factor * x_range
    467 except ZeroDivisionError:  # not enough samples

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/pysumreg/sum_registers.py:298, in SummationRegisters.sigma(self)
    283 @property
    284 def sigma(self):
    285     r"""
    286     The y-weighted variance (:math:`\sigma_c^2`) of :math:`(x, y)`.
    287 
   (...)
    296     See: :meth:`centroid`
    297     """
--> 298     return math.sqrt((self.XXY - self.centroid * self.XY) / self.Y)

ValueError: math domain error

In [26]: 

```

</details>

**Comment by prjemian** [comment]
example data:

```text
    x      y
 -8.322 -0.047
 -7.822 -0.070
 -7.322 -0.001
 -6.822  0.081
 -6.322 -0.041
 -5.822  0.058
 -5.322 -0.044
 -4.822 -0.025
 -4.322  0.077
 -3.822  0.023
 -3.322  0.054
 -2.822  0.098
 -2.322  0.018
 -1.822  0.098
 -1.322  0.420
 -0.822  0.721
 -0.322  0.930
  0.178  1.079
  0.678  0.764
```

**Comment by prjemian** [comment]
No problem here.  Use in `apstools.plans.lineup2()` must call the `.clear()` method before each new use.
